# Используем современный синтаксис без версии
# version устарела в Docker Compose v2+

services:
  # Redis для очередей задач
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  # Telegram Bot
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_USER_ID=${ADMIN_USER_ID}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    volumes:
      - shared_files:/tmp/shared
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Video Worker
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    volumes:
      - shared_files:/tmp/shared
    networks:
      - app-network
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1200M
        reservations:
          memory: 256M

  # Redis Commander для мониторинга (опционально)
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=redis:redis:6379
    depends_on:
      - redis
    networks:
      - app-network
    profiles:
      - monitoring

  # Watchtower для автообновления
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_INCLUDE_STOPPED=true
    profiles:
      - auto-update

volumes:
  redis_data:
    driver: local
  shared_files:
    driver: local

networks:
  app-network:
    driver: bridge 