version: '3.8'

services:
  telegram-bot:
    image: ghcr.io/piton-vas/video_summarize_bot:latest
    container_name: video_summarize_bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_USER_ID=${ADMIN_USER_ID}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info
      - WATCHTOWER_REGISTRY_USERNAME=${REPO_USER}
      - WATCHTOWER_REGISTRY_PASSWORD=${REPO_PASS}
      - WATCHTOWER_REGISTRY_URL=https://ghcr.io
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker:/root/.docker:ro
    command: >
      --interval 60
      --cleanup
      --label-enable
      --debug
      --registry-credentials
    restart: unless-stopped
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  bot-logs: 