version: '3.8'

services:
  telegram-bot:
    image: ghcr.io/piton-vas/video_summarize_bot:latest
    container_name: video_summarize_bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info
      - REPO_USER=${REPO_USER}
      - REPO_PASS=${REPO_PASS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json:ro
    command: --interval 60 --cleanup --label-enable
    restart: unless-stopped
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  bot-logs: 