version: '3.8'

services:
  telegram-bot:
    image: your-dockerhub-username/video-summarize-bot:latest
    container_name: video_summarize_bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  bot-logs: 